### PR TITLE
Replaced JavaScript service worker with TypeScript service worker

### PR DESCRIPTION
**Pull request by alehuo**
Replaced JavaScript service worker with TypeScript service worker. Updated `index.tsx` to reflect this change. Let's unregister the service worker as default.

### CODE REVIEW

**Comment by strax** [comment]
Do we even need the file if we’re just deregistering the SW? I mean why not just delete the whole functionality since this is not in production?

**Comment by alehuo** [comment]
We can either delete the functionality as a whole, or unregister it. I think it's up to the fact if we need a service worker sometime in the future.

Service worker is opt-in starting from CRA 2.0.

**Comment by strax** [comment]
We can always add the SW back if we need it, I think this is analogous to commenting out code to preserve it for the future which is unnecessary with git.

**Comment by cxcorp** [comment]
Gonna delete the service worker.

**Pull request closed without merging**
